version: '3.8'

networks:
  gv-network:
    driver: bridge

volumes:
  pgdata:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gv-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - gv-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - gv-network
